const fs = require('fs');

const dkey = {
  bt_cancel: '',
  bt_delete: '',
  bt_overlay_product_update: '',
  bt_save: '',
  bt_send: '',
  label_all: '',
  label_category: '',
  label_delist: '',
  label_more_operation: '',
  label_preview_product_name: '',
  label_price: '',
  label_promotion_off: '',
  label_promotion_sold: '',
  label_publish: '',
  label_set_shipping_fee: '',
  label_sold_out: '',
  label_stock: '',
  label_unlisted: '',
  label_unlisted_count: '',
  label_variations: '',
  label_weight: '',
  label_wholesale: '',
  marketing_center_shopee_campaign_title: '',
  ps_add_new_product: '',
  ps_are_you_sure_to_delete_product: '',
  ps_attributes: '',
  ps_btn_text_reach_limit_tool_tip: '',
  ps_cannot_edit_product_of_in_vacation_mode_label: '',
  ps_csv_variation_origin_price: '',
  ps_delete_product: '',
  ps_label_add: '',
  ps_marketing_center_shopee_flashsale_title: '',
  ps_mass_shipping_fee_3: '',
  ps_msg_batch_delist_confirm_title: '',
  ps_msg_batch_publish_success: '',
  ps_msg_delist_confirm_content: '',
  ps_msg_delist_confirm_title: '',
  ps_msg_delist_success: '',
  ps_msg_not_delist_error_content: '',
  ps_msg_not_delist_for_has_promotion_content: '',
  ps_msg_not_publish_for_reach_limit_content: '',
  ps_msg_not_publish_for_status_error_content: '',
  ps_msg_not_publish_title: '',
  ps_msg_publish_reach_limit: '',
  ps_msg_single_publish_success_content: '',
  ps_msg_unlisted_frozen: '',
  ps_msg_upgrade_account_link: '',
  ps_msg_upgrade_can_publish: '',
  ps_msg_upgrade_reach_limit: '',
  ps_seller_listing_limit_max_tooltip_label: '',
  ps_seller_listing_limit_max_tooltip_text: '',
  ps_seller_listing_limit_rule: '',
  ps_sip_suffix_label_current_net_price: '',
  ps_sku_parent_short: '',
  ps_sku_short: ''
};

const origin = {
  /** @Login **/
  ps_return_export_return_reason_functional_dmg: 'powerseller',
  ps_new_address_prefix_label: 'powerseller',
  ps_edit_img: 'powerseller',
  ps_edit_img_description: 'powerseller',
  ps_attr_product_image_help_label: 'powerseller',
  ps_img_indicator: 'powerseller',
  ps_attr_basic_information: 'powerseller',
  label_preview_product_name: 'ios',
  ps_view_in_mall: 'powerseller',
  label_product_desc: 'ios',
  sl_error_product_name_too_long: 'listing',
  sl_error_product_name_too_short: 'listing',
  ps_error_product_name_invalid_characters: 'powerseller',
  label_category: 'ios',
  ps_attributes: 'powerseller',
  label_optional: 'ios',
  ps_attr_product_size_chart_label: 'powerseller',
  ps_attr_price_and_inventory: 'powerseller',
  label_variation: 'web',
  label_variations: 'web',
  label_model_name: 'ios',
  label_refund_status: 'web',
  msg_pending_return_seller_1: 'web',
  ps_sku_short: 'powerseller',
  label_price: 'ios',
  label_stock: 'ios',
  ps_label_example: 'powerseller',
  ps_add_variation: 'powerseller',
  label_wholesale: 'ios',
  ps_wholesale_price_tier: 'powerseller',
  label_wholesale_tier: 'ios',
  lbl_wholesale_tier_min_placeholder: 'ios',
  lbl_wholesale_tier_max_placeholder: 'ios',
  lbl_wholesale_unitprice: 'ios',
  ps_attr_shipping: 'powerseller',
  ps_msg_delist_failed: 'powerseller',

  /** product category - start */
  ps_add_new_product_desc: 'powerseller',
  ps_lable_currently_selected: 'powerseller',
  ps_product_category_msg_no_selected: 'powerseller',
  ps_label_categories_name: 'powerseller',
  /** product category - end */

  label_weight: 'web',
  ps_parcel_size: 'powerseller',
  label_width: 'web',
  label_length: 'web',
  label_height: 'web',
  label_shipping_fee: 'web',
  label_enabled: 'web',
  ps_label_max: 'powerseller',
  label_unit_kg: 'web',
  ps_logistics_product_level_desc: 'powerseller',

  ps_attr_others: 'powerseller',
  label_pre_order: 'ios',
  label_condition: 'ios',
  ps_sku_parent_short: 'powerseller',
  label_starting_from: 'web',
  ps_label_i_need: 'powerseller',
  label_no: 'web',
  label_yes: 'web',
  label_unit_gram: 'web',
  label_delist: 'powerseller',
  bt_cancel: 'ios',
  bt_delete: 'ios',
  bt_overlay_product_update: 'ios',
  bt_menu_edit_product: 'ios',
  label_comments: 'web',
  label_reviews: 'web',
  ps_label_days_to_ship_preorder_range: 'powerseller',
  label_item_condition_new: 'ios',
  label_item_condition_used: 'ios',
  ps_shopee_supported_logistics: 'powerseller',
  label_promotion_sold: 'web',
  ps_label_likes: 'powerseller',
  label_all: 'ios',
  msg_no_buyer_give_you_rating: 'web',

  ps_label_cc_installment: 'powerseller',
  ps_cc_installment_tenures_selected_now: 'powerseller',
  ps_cc_installment_smid_status_verified: 'powerseller',
  ps_cc_installment_set_tenures: 'powerseller',
  ps_cc_installment_product_setting_tips: 'powerseller',
  ps_cc_installment_tenures_stages: 'powerseller',
  ps_cc_installment_product_prompt_msg: 'powerseller',
  ps_modal_buttons_to_toggle_on: 'powerseller',

  ps_mass_shipping_fee_3: 'powerseller',
  label_i_will_cover_shipping_fee: 'web',
  ps_attr_product_image_help_tooltips: 'powerseller',
  ps_attr_tooltip_product_name: 'powerseller',
  ps_attributes_no_results: 'powerseller',
  ps_attributes_not_in_list: 'powerseller',
  ps_attributes_set_your_own: 'powerseller',
  ps_attributes_search_for: 'powerseller',
  bt_save: 'ios',
  label_close_web_popup: 'ios',
  text_packing_size_description: 'web',
  label_title_review_ban_product_prompt: 'ios',
  ps_msg_banned_detail: 'powerseller',
  ps_product_cannot_edit: 'powerseller',
  ps_product_cannot_edit_description: 'powerseller',
  ps_wrong_category_warning_message: 'powerseller',
  ps_edit_tool_tip_title: 'powerseller',
  ps_edit_tool_tip_content: 'powerseller',
  ps_edit_tool_tip_content_self: 'powerseller',
  ps_label_shipping_fee_calculated_by_size: 'powerseller',
  label_apply: 'web',
  msg_explain_i_will_cover_shipping_fee: 'web',
  ps_learn_more: 'powerseller',
  ps_attr_tooltip_product_attributes_invalid: 'powerseller',
  ps_attr_tooltip_product_attributes: 'powerseller',
  title_set_attribute_list: 'ios',
  ps_wrong_category_revise_tooltip: 'powerseller',
  msg_video_not_supported: 'pc',
  label_cover_photo: 'ios',
  sl_label_cover_video: 'listing',
  sl_video_pixel_limit: 'listing',
  sl_video_duration_limit: 'listing',
  sl_video_format_limit: 'listing',
  ps_add_more_img: 'powerseller',
  ps_enable_variation: 'powerseller',
  ps_wholesale_product_detail_notice: 'powerseller',
  sl_wholesale_clear_taxable_seller_tip: 'listing',
  ps_wholesale_lowest_ratio_notice: 'powerseller',
  ps_api_error_update_product_wholesale_limit: 'powerseller',
  ps_label_days_to_ship_no_preorder: 'powerseller',
  label_publish: 'powerseller',

  ps_label_variation1: 'powerseller',
  ps_label_variation_option: 'powerseller',
  ps_label_tips: 'powerseller',
  ps_label_variation2: 'powerseller',
  ps_label_variation_info: 'powerseller',
  ps_label_variation_batch_edit: 'powerseller',
  ps_label_variation_list: 'powerseller',
  ps_label_default_variation_name: 'powerseller',
  ps_label_add: 'powerseller',
  ps_label_apply_to_all: 'powerseller',
  ps_label_add_variation_option: 'powerseller',
  ps_label_variation_name_placeholder: 'powerseller',
  ps_label_variation_option_placeholder: 'powerseller',
  ps_attr_tooltip_product_price: 'powerseller',
  ps_upload_folder_only_in_chrome: 'powerseller',
  ps_error_msg_exceed_amount_limit: 'powerseller',
  ps_error_product_image_pixel_minimum: 'powerseller',
  ps_error_msg_invalid_image_aspect: 'powerseller',
  ps_error_msg_invalid_image_size: 'powerseller',
  ps_error_msg_file_oversize: 'powerseller',
  ps_error_msg_invalid_file: 'powerseller',
  ps_not_allowed_upload_folder: 'powerseller',
  ps_error_msg_cannot_upload: 'powerseller',
  sl_alarm_video_pending: 'listing',
  alert_discard_change: 'ios',
  ps_btn_discard_vn: 'powerseller',
  ps_error_msg_variations_exceeded: 'powerseller',
  label_unlisted: 'powerseller',
  label_unlisted_count: 'powerseller',
  label_unlisted_frozen: 'powerseller',
  label_unlisted_unlist: 'powerseller',
  label_more_operation: 'powerseller',
  ps_msg_publish_reach_limit: 'powerseller',
  ps_message_delist_is_promotion: 'powerseller',
  ps_msg_unlisted_frozen: 'powerseller',
  ps_msg_delist_success: 'powerseller',
  ps_msg_delist_confirm_title: 'powerseller',
  ps_msg_delist_confirm_content: 'powerseller',
  ps_msg_single_publish_success: 'powerseller',
  ps_msg_single_publish_success_title: 'powerseller',
  ps_msg_single_publish_success_content: 'powerseller',
  ps_msg_upgrade_account_link: 'powerseller',
  ps_msg_batch_publish_success: 'powerseller',
  ps_msg_not_publish_title: 'powerseller',
  ps_msg_not_publish_for_reach_limit_content: 'powerseller',
  ps_msg_not_publish_for_status_error_content: 'powerseller',
  ps_msg_batch_delist_confirm_title: 'powerseller',
  ps_msg_not_delist_error_content: 'powerseller',
  ps_msg_not_delist_for_has_promotion_content: 'powerseller',
  ps_msg_upgrade_reach_limit: 'powerseller',
  ps_msg_upgrade_can_publish: 'powerseller',
  ps_btn_text_reach_limit_tool_tip: 'powerseller',
  ps_logistics_calculated_shipping_fee_based_on_weight: 'powerseller',
  ps_logistics_calculated_shipping_fee_based_on_weight_and_dimensions: 'powerseller',
  ps_logistics_btn_apply_and_enable_channel: 'powerseller',
  sl_tip_product_accurate_dimension: 'listing',
  ps_variation_images_number_error: 'powerseller',
  label_shipping_fee_included: 'web',
  msg_explain_shipping_fee_included: 'web',
  label_enable_shipping_option: 'web',
  msg_explain_one_shipping_option: 'web',
  ps_product_logistics_settings_help: 'powerseller',
  text_edit_item_success: 'ios',
  hud_error_exceed_item_limit: 'ios',
  // error_product_list_limit_exceed: 'ios',
  hud_error_general_error: 'ios',
  ps_success_delisted: 'powerseller',
  msg_listed_successfully: 'web',
  msg_please_input_value_between_min_and_max: 'web',
  ps_pre_order_placeholder_3: 'powerseller',
  ps_pre_order_placeholder_1: 'powerseller',
  ps_pre_order_placeholder_2: 'powerseller',
  ps_recommend_categories: 'powerseller',
  ps_all_categories: 'powerseller',
  ps_error_msg_logistics_size_invalid: 'powerseller',
  ps_error_msg_cannot_upload_image: 'powerseller',
  ps_delete_product: 'powerseller',
  ps_are_you_sure_to_delete_product: 'powerseller',
  ps_cannot_edit_product_of_in_vacation_mode_label: 'powerseller',
  ps_label_default_option_name: 'powerseller',
  ps_variation_info_tip: 'powerseller',
  ps_discount_product_entitled_in_discount: 'powerseller',
  label_promotion_off: 'web',
  hud_error_add_product_preorder_dts: 'ios',
  ps_sku_duplicate_error: 'powerseller',
  ps_error_invalid_duplicate_products: 'powerseller',
  ps_upload_rapid_control_warning_without_time: 'powerseller',
  ps_network_error_try_later: 'powerseller',
  ads_date_to: 'ads-portal',
  ps_promo_stock: 'powerseller',
  ps_label_banned_product_reason: 'powerseller',
  label_product_desc_placeholder: 'ios',
  caption_choose_category: 'ios',
  txt_wholesale_description: 'ios',
  sl_wholesale_disable_taxable_seller_tip: 'listing',
  ps_label_width_abbreviation: 'powerseller',
  ps_label_height_abbreviation: 'powerseller',
  ps_label_length_abbreviation: 'powerseller',
  label_special_sku: 'web',
  ps_logistics_btn_add_shipping_options: 'powerseller',
  ps_pre_order_notice: 'powerseller',
  ps_label_basic_dts_notice:'powerseller',
  ps_label_basic_dts_no_preorder_notice: 'powerseller',
  ps_label_dts_calculation_rules_notice:'powerseller',
  alert_preorder_dts: 'ios',
  label_set_shipping_fee: 'web',
  ps_error_requires_weight: 'powerseller',
  ps_error_requires_weight_tooltip: 'powerseller',
  ps_label_min: 'powerseller',
  ps_logistic_bundle_deal_tips: 'powerseller',
  ps_product_edit_add_on_deal_shipping_tips: 'powerseller',
  sl_channel_spx_cannot_turned_off_tips: 'listing',
  hud_item_desc_too_short: 'ios',
  ps_error_terminal_white_space_disallowed: 'powerseller',
  ps_error_msg_price_lower2: 'powerseller',
  hud_error_add_product_modelname_same: 'ios',
  ps_error_option_duplicate: 'powerseller',
  msg_enable_shipping_channel: 'web',
  ps_btn_save_and_publish: 'powerseller',
  ps_btn_save_and_delist: 'powerseller',
  ps_invalid_logistic: 'powerseller',
  error_wholesale_min_count: 'ios',
  // alert_wholesale_original_price_lower: 'ios',
  label_seller_listing_validate_price_origin: 'react-native',
  error_wholesale_previous_price: 'ios',
  // error_wholesale_invalid_range: 'ios',
  sl_wholesale_validate_max_bigger_than_min: 'listing',
  sl_wholesale_unit_price_after_tax: 'listing',
  sl_wholesale_after_tax_price_tip: 'listing',
  sl_wholesale_validate_max_count_limit: 'listing',
  sl_wholesale_product_promotion_tips: 'listing',
  sl_wholesale_reach_max_count_limit_need_delete_following: 'listing',
  label_unfollow: 'web',
  label_follow: 'web',
  label_following: 'web',
  label_sold_out: 'ios',
  ps_comment_message_remove_success: 'powerseller',
  ps_label_confirm_delete: 'powerseller',
  ps_msg_single_publish_error: 'powerseller',
  ps_warn_shipping_fee_in_bundle_deal: 'powerseller',
  ps_volume_limit_exceeded: 'powerseller',
  ps_volume_weight_limit_exceeded: 'powerseller',
  ps_label_require_category: 'powerseller',
  ps_label_overheight: 'powerseller',
  ps_label_overlength: 'powerseller',
  ps_label_overwidth: 'powerseller',
  ps_txt_preorder_description_sg: {
    source: 'powerseller',
    regions: ['sg']
  },
  ps_txt_preorder_description_tw: {
    source: 'powerseller',
    regions: ['tw']
  },
  ps_txt_preorder_description_id: {
    source: 'powerseller',
    regions: ['id']
  },
  ps_txt_preorder_description_my: {
    source: 'powerseller',
    regions: ['my']
  },
  ps_txt_preorder_description_th: {
    source: 'powerseller',
    regions: ['th']
  },
  ps_txt_preorder_description_ph: {
    source: 'powerseller',
    regions: ['ph']
  },
  ps_txt_preorder_description_vn: {
    source: 'powerseller',
    regions: ['vn']
  },
  ps_shipping_promotion_tip: 'powerseller',
  ps_label_details: 'powerseller',
  ps_product_upload_description: 'powerseller',
  ps_add_new_product: 'powerseller',
  ps_browse_img: 'powerseller',
  ps_drag_drop_img: 'powerseller',
  ps_label_upload_failed: 'powerseller',
  ps_upload_image_size: 'powerseller',
  ps_upload_image_format: 'powerseller',
  ps_upload_image_dimension: 'powerseller',
  ps_error_msg_duplicate_img: 'powerseller',
  ps_edit_tool_tip_link: 'powerseller',
  sl_unpubished_to_publish_additional: 'listing',
  ps_edit_text_reach_limit_not_publish: 'powerseller',
  ps_label_current_promotion: 'powerseller',
  ps_marketing_center_shopee_flashsale_title: 'powerseller',
  marketing_center_shopee_campaign_title: 'powerseller',
  marketing_center_self_discount_title: 'powerseller',
  ps_itemmodel_exceed: 'powerseller',
  label_overweight: 'web',
  ps_error_msg_stock_range: 'powerseller',
  ps_error_msg_price_upper: 'powerseller',
  ps_attr_product_size_chart_tooltips: 'powerseller',
  error_attribute_mandatory: 'ios',
  ps_error_attribute_needs_revision: 'powerseller',
  error_attribute_list_input_number: 'ios',
  msg_sth_is_wrong: 'web',
  title_attribute_self_define: 'ios',
  ps_price_not_editable_tips: 'powerseller',
  ps_weight_invalid: 'powerseller',
  ps_volumetric_weight_exceed: 'powerseller',
  label_num_star: 'web',
  ps_width_invalid: 'powerseller',
  ps_length_invalid: 'powerseller',
  ps_height_invalid: 'powerseller',
  ps_parcel_size_invalid: 'powerseller',
  sl_error_duration_invalid: 'listing',
  sl_error_piexl_invalid: 'listing',
  ps_mass_update_dts_flash_sale_description: 'powerseller',
  ps_tooptip_unpublished_dts_lock: 'powerseller',
  ps_flashsale_dts_limitation: 'powerseller',
  bt_reply: 'ios',
  bt_send: 'ios',
  msg_rating_reply_only: 'web',
  ps_error_msg_not_null: 'powerseller',
  ps_sale_price: 'powerseller',
  ps_price_not_editable: 'powerseller',
  alert_operation_param: 'web',
  ps_variation_option_lock_tips: 'powerseller',
  ps_seller_listing_limit_max_tooltip_label: 'powerseller',
  ps_seller_listing_limit_max_tooltip_text: 'powerseller',
  ps_seller_listing_limit_rule: 'powerseller',
  ps_two_tier_variation_lock_tips: 'powerseller',
  sl_popover_add_variation_in_shopee_warehouse: 'listing',
  sl_popover_selected_in_shopee_warehouse: 'listing',
  ps_error_product_image_minimum_more: 'powerseller',
  ps_error_product_image_minimum: 'powerseller',
  // ps_video_upload_not_supported: 'powerseller',
  label_disabled: 'web',
  label_discount: 'web',
  caption_product_detail: 'ios',
  ps_error_msg_invalid_category: 'powerseller',
  ps_error_item_desc_too_long: 'powerseller',
  sl_error_product_description_too_short: 'listing',
  sl_error_product_description_too_long: 'listing',

  // ====================== tax price label ===========================
  ps_csv_variation_origin_price: 'powerseller',
  ps_price_after_tax: 'powerseller',
  ps_price_after_tax_tips: 'powerseller',
  ps_original_discount_price: 'powerseller',
  ps_discount_price_after_tax: 'powerseller',
  ps_message_promotion_price_not_edit: 'powerseller',
  ps_message_upcoming_promotion_price_not_edit: 'powerseller',
  ps_message_list_page_tax_price: 'powerseller',

  sl_shipping_channel_enabled_exclusive_tips: 'listing',
      // ====================== Logistics Name and Description ===========================
  label_premium_express: 'web',
  label_normal_express: 'web',
  label_post_registered: 'web',
  label_post_normal: 'web',
  label_post_special: 'web',
  label_china_ems: 'web',
  label_china_post: 'web',
  label_directlink: 'web',
  label_dpex: 'web',
  label_ec_firstclass: 'web',
  label_hong_kong_post: 'web',
  label_malaysia_post: 'web',
  label_malaysia_post_posdaftar: 'web',
  label_postnl_international: 'web',
  label_sf_express: 'web',
  label_singpost_normal: 'web',
  label_singpost_popstation: 'web',
  label_singpost_registered: 'web',
  label_singpost_smartpac: 'web',
  label_standard_express: 'web',
  label_registered_air_mail: 'web',
  label_air_mail: 'web',
  label_postlaju_east: {
    source: 'web',
    regions: ['my']
  },
  label_postlaju_west: {
    source: 'web',
    regions: ['my']
  },
  label_gdex_east: {
    source: 'web',
    regions: ['my']
  },
  label_gdex_west: {
    source: 'web',
    regions: ['my']
  },
  label_lwe_hk: 'web',
  label_buylogic: 'web',
  label_thaipost_registered: {
    source: 'web',
    regions: ['th']
  },
  label_cj_gls: {
    source: 'web',
    regions: ['th']
  },
  label_dhl: {
    source: 'web',
    regions: ['th']
  },
  label_fedex: {
    source: 'web',
    regions: ['th']
  },
  label_yto_normal: {
    source: 'web',
    regions: ['tw']
  },
  label_yto_711: {
    source: 'web',
    regions: ['tw']
  },
  label_desc_yto_normal: {
    source: 'web',
    regions: ['tw']
  },
  label_desc_yto_711: {
    source: 'web',
    regions: ['tw']
  },
  label_desc_normal_express: {
    source: 'web',
    regions: ['sg', 'tw']
  },
  label_desc_post_normal: {
    source: 'web',
    regions: ['sg', 'tw']
  },
  label_desc_post_registered: {
    source: 'web',
    regions: ['sg', 'tw']
  },
  label_desc_post_special: {
    source: 'web',
    regions: ['sg', 'tw']
  },
  label_desc_premium_express: {
    source: 'web',
    regions: ['sg', 'tw']
  },
  label_desc_registered_air_mail_yto: {
    source: 'web',
    regions: ['sg', 'tw']
  },
  label_desc_standard_express_dpex: {
    source: 'web',
    regions: ['sg', 'tw']
  },
  label_desc_standard_express_lwe: {
    source: 'web',
    regions: ['sg', 'tw']
  },
  label_desc_standard_express_yto: {
    source: 'web',
    regions: ['sg', 'tw']
  },
  label_standard_express_dpex: 'web',
  label_standard_express_lwe: 'web',
  // =================================================Logistics Name and Description end=============================================

  // =================================================sip primary shop===============================================================
  ps_sip_label_sum_and_primary_stock: 'powerseller',
  ps_sip_label_sum_and_primary_stock_tip: 'powerseller',
  ps_sip_suffix_label_current_primary_stock: 'powerseller',
  ps_sip_suffix_label_current_primary_stock_tip: 'powerseller',
  ps_sip_price_and_primary_stock_btn: 'powerseller',
  ps_sip_sku_primary_table_caption: 'powerseller',
  ps_sip_total_stock_tip: 'powerseller',
  ps_sip_suffix_label_current_net_price: 'powerseller',
  ps_sip_suffix_label_current_net_price_tip: 'powerseller',
  ps_primary_stock: 'powerseller',
  ps_variation_name: 'powerseller',
  ps_label_sale_info: 'powerseller',
  ps_label_media_management: 'powerseller',
  ps_label_product_images: 'powerseller',
  sl_label_product_video: 'listing',
  ps_caption_product_category: 'powerseller',
  psd_loading: 'data-center',
  ps_product_category_search_no_result: 'powerseller',
  msg_item_enable_shipping_channel_18035: {
    source: 'web',
    regions: ['sg']
  },
  msg_item_enable_shipping_channel_10007: {
    source: 'web',
    regions: ['sg']
  },
  msg_item_enable_shipping_channel_19100: {
    source: 'web',
    regions: ['sg']
  },
  label_bae_size_small: 'web',
  label_bae_size_medium: 'web',
  label_bae_size_large: 'web',
  label_lbc_size_medium: 'web',
  label_lbc_size_large: 'web',
  label_2go_size_small: 'web',
  label_2go_size_small_description: 'web',
  label_2go_size_medium: 'web',
  label_2go_size_medium_description: 'web',
  label_2go_size_large: 'web',
  label_2go_size_large_description: 'web',
  label_bae_size_medium_description: 'web',
  label_bae_size_small_description: 'web',
  label_bae_size_large_description: 'web',
  label_lbc_size_medium_description: 'web',
  label_lbc_size_large_description: 'web',
  ps_error_product_image_max: 'powerseller',
  ps_label_view_effect: 'powerseller',
  sl_label_image: 'listing',
  title_shop_settings: 'ios',
  ps_promo_stock_wms_stock_sync: 'powerseller',
  sl_wms_stock_sync_tips: 'listing',
  ps_label_reserved: 'powerseller',
  ps_label_normal_stock: 'powerseller',
  ps_label_reserved_stock: 'powerseller',
  ps_message_promotion_stock_not_edit: 'powerseller',
  ps_message_reserved_stock_by_campaign: 'powerseller',
  ps_label_variation_name_placeholder_two: 'powerseller',
  ps_label_variation_option_placeholder_two: 'powerseller',

  // product-view action button label
  ads_states_keyword_buy: 'ads-portal',
  ads_states_keyword_deleted: 'ads-portal',
  ads_states_keyword_scheduled: 'ads-portal',
  ads_states_keyword_ongoing: 'ads-portal',
  ads_states_keyword_ended: 'ads-portal',
  ads_states_keyword_paused: 'ads-portal',
  ads_reminder_too_high_sugg_price: 'ads-portal',
  ads_entry_point_help: 'ads-portal',
  ads_entry_point_feedback: 'ads-portal',

  // product-view action button label
  ads_states_targeting_buy: 'ads-portal',
  ads_states_targeting_deleted: 'ads-portal',
  ads_states_targeting_scheduled: 'ads-portal',
  ads_states_targeting_ongoing: 'ads-portal',
  ads_states_targeting_ended: 'ads-portal',
  ads_states_targeting_paused: 'ads-portal',

  ps_error_msg_delete_variation: 'powerseller',

  ps_listing_virtual_package_edit_no_support: 'powerseller',
  // product banned reason
  sl_label_banned_product_reason: 'listing',

  /** item price for SIP */
  sl_itemprice_info_auto_cal: 'listing',
  sl_itemprice_info_quoted: 'listing',
  sl_itemprice_info_quoted_change: 'listing',
  sl_itemprice_label_auto_cal: 'listing',
  sl_itemprice_label_quoted: 'listing',
  sl_itemprice_tooltip: 'listing',
  sl_itemprice_name: 'listing',
  sl_itemprice_error_invalid_duration: 'listing',
  sl_itemprice_info_change_once_each_day: 'listing',
  sl_itemprice_edit_disabled_in_changed: 'listing',
  sl_itemprice_edit_disabled_in_ongoing_promotion: 'listing',
  sl_itemprice_edit_disabled_in_upcoming_promotion: 'listing',
  sl_tiemprice_edit_disabled_in_new_model: 'listing',

  // cc installment tip
  sl_cc_installment_tip_number_format_title: 'listing',
  sl_cc_installment_tip_number_format_desc: 'listing',
  sl_cc_installment_tip_force_set_title: 'listing',
  sl_cc_installment_tip_force_set_desc: 'listing',

  // masking channel
  ps_others: 'powerseller',
  sl_shipping_channel_enabled_exclusive_tips: 'listing',

  // mpsku
  sl_label_mtsku_price: 'listing',
  sl_action_open_mtsku_original_text: 'listing',
  sl_action_close_mtsku_original_text: 'listing',
  sl_action_open_mtsku_original_variation: 'listing',
  sl_action_close_mtsku_original_variation: 'listing',
  sl_mpsku_stock_modify_redirect_tips: 'listing',

  // mtsku
  sl_mtsku_label_weight_and_dimension: 'listing',
  sl_mtsku_error_variation_too_long: 'listing',
  sl_mtsku_error_variation_too_short: 'listing',
  sl_mtsku_error_option_too_long: 'listing',
  sl_mtsku_error_option_too_short: 'listing',
  sl_button_create: 'listing',
  sl_button_save: 'listing',
  sl_button_create_successfully: 'listing',
  sl_button_save_successfully: 'listing',
  sl_mtsku_list_title: 'listing',
  sl_label_days_to_ship: 'listing',
  sl_text_days_to_ship: 'listing',
  // sip pff
  sl_sip_seller_total_stock: 'listing',
  sl_sip_seller_primary_stock: 'listing',
  
  ps_myproduct_tip_cc_installment: 'powerseller',
  ps_myproduct_tip_cc_installment_price_limit: 'powerseller',
  ps_cc_installment_help_link: 'powerseller',
  sp_text_cc_installment: 'powerseller',

  // masking channel
  ps_others: 'powerseller',
  sl_shipping_channel_enabled_exclusive_tips: 'listing',
};


const res = {};

Object.keys(origin).forEach(key => {
  if (dkey[key] === '') {
    return;
  }
  res[key] = origin[key];
})

fs.writeFileSync('./res.js', `module.exports = ${JSON.stringify(res)}`);